### ISSUE TITLE
Doesn't this work for SQLServer yet

### ISSUE THREAD

**Issue by pbuxtonccuk** [zlzforever/ClickHouseMigrator#2]
I can't get this to work, it claims its not written yet.....

I installed it following your instructions, would be great if you could advise, if it is supposed to work.

thanks
Paul

**Comment by zlzforever** [comment]
i will check it this week end.

**Comment by zlzforever** [comment]
@pbuxtonccuk have a try the new version

**Comment by pbuxtonccuk** [comment]
Didn't want to re-open this, but it doesn't work.  On startup, the utility outputs an INFO line of what look like the parameters it is using, but they bear no resemblance mine...  almost looks hardcoded.
