### ISSUE TITLE
目标数据库名称大小写问题

### ISSUE THREAD

**Issue by hanhoc** [zlzforever/ClickHouseMigrator#3]
用--targetdb指定数据库名称时，使用大写如--targetdb ABC或是--targetdb "ABC"时，在clickhouse会创建名称了小写的abc数据库，请问怎样才能指定大写名称

**Comment by zlzforever** [comment]
--ignorecase: ignore the word case in clickhouse, default value: true

**Comment by hanhoc** [comment]
1.不加参数
2.--ignorecase
3.--ignorecase false
4.--ignorecase true
以上几种执行都不报错，但结果全部为小写

**Comment by zlzforever** [comment]
@hanhoc 已发布 1.0.8, 参数略有变化如 --targetdb 改为 --targetd

**Comment by hanhoc** [comment]
测试了，问题解决了，谢谢
