### ISSUE TITLE
I wanted to know if clickhousrake could achieve real time synchronization of data

### ISSUE THREAD

**Issue by kitty-eu-org** [zlzforever/ClickHouseMigrator#5]
Hi.
  I wanted to know if clickhousrake could achieve real time synchronization of data,For example, when my SQL Server data is being updated or dalETE, can the corresponding data of Clickhouse be updated? In addition, is there any guarantee of breakpoint continuation?

**Comment by kitty-eu-org** [comment]
@zlzforever

**Comment by zlzforever** [comment]
Maybe the solution is https://github.com/alibaba/canal or https://github.com/brokercap/Bifrost or wait the 
 PR https://github.com/ClickHouse/ClickHouse/pull/10851
